version: '3.9'
networks:
  app-tier:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - app-tier
    depends_on:
      - monitor
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
  monitor:
    networks:
      - app-tier
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma:/app/data
volumes:
  nginx_secrets: null
  uptime-kuma: null
